// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: optimizer/v1/optimizer.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // Add other parameters like duration for metrics, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizeRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *OptimizeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type OptimizeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Recommended resources could be added here
	RecommendedCpu    map[string]string `protobuf:"bytes,3,rep,name=recommended_cpu,json=recommendedCpu,proto3" json:"recommended_cpu,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RecommendedMemory map[string]string `protobuf:"bytes,4,rep,name=recommended_memory,json=recommendedMemory,proto3" json:"recommended_memory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OptimizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OptimizeResponse) GetRecommendedCpu() map[string]string {
	if x != nil {
		return x.RecommendedCpu
	}
	return nil
}

func (x *OptimizeResponse) GetRecommendedMemory() map[string]string {
	if x != nil {
		return x.RecommendedMemory
	}
	return nil
}

var File_optimizer_v1_optimizer_proto protoreflect.FileDescriptor

const file_optimizer_v1_optimizer_proto_rawDesc = "" +
	"\n" +
	"\x1coptimizer/v1/optimizer.proto\x12\foptimizer.v1\"X\n" +
	"\x0fOptimizeRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x92\x03\n" +
	"\x10OptimizeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12[\n" +
	"\x0frecommended_cpu\x18\x03 \x03(\v22.optimizer.v1.OptimizeResponse.RecommendedCpuEntryR\x0erecommendedCpu\x12d\n" +
	"\x12recommended_memory\x18\x04 \x03(\v25.optimizer.v1.OptimizeResponse.RecommendedMemoryEntryR\x11recommendedMemory\x1aA\n" +
	"\x13RecommendedCpuEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16RecommendedMemoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012_\n" +
	"\x10OptimizerService\x12K\n" +
	"\bOptimize\x12\x1d.optimizer.v1.OptimizeRequest\x1a\x1e.optimizer.v1.OptimizeResponse\"\x00B.Z,neuralops/api/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_optimizer_proto_rawDescOnce sync.Once
	file_optimizer_v1_optimizer_proto_rawDescData []byte
)

func file_optimizer_v1_optimizer_proto_rawDescGZIP() []byte {
	file_optimizer_v1_optimizer_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_optimizer_proto_rawDesc), len(file_optimizer_v1_optimizer_proto_rawDesc)))
	})
	return file_optimizer_v1_optimizer_proto_rawDescData
}

var file_optimizer_v1_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_optimizer_v1_optimizer_proto_goTypes = []any{
	(*OptimizeRequest)(nil),  // 0: optimizer.v1.OptimizeRequest
	(*OptimizeResponse)(nil), // 1: optimizer.v1.OptimizeResponse
	nil,                      // 2: optimizer.v1.OptimizeResponse.RecommendedCpuEntry
	nil,                      // 3: optimizer.v1.OptimizeResponse.RecommendedMemoryEntry
}
var file_optimizer_v1_optimizer_proto_depIdxs = []int32{
	2, // 0: optimizer.v1.OptimizeResponse.recommended_cpu:type_name -> optimizer.v1.OptimizeResponse.RecommendedCpuEntry
	3, // 1: optimizer.v1.OptimizeResponse.recommended_memory:type_name -> optimizer.v1.OptimizeResponse.RecommendedMemoryEntry
	0, // 2: optimizer.v1.OptimizerService.Optimize:input_type -> optimizer.v1.OptimizeRequest
	1, // 3: optimizer.v1.OptimizerService.Optimize:output_type -> optimizer.v1.OptimizeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_optimizer_v1_optimizer_proto_init() }
func file_optimizer_v1_optimizer_proto_init() {
	if File_optimizer_v1_optimizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_optimizer_proto_rawDesc), len(file_optimizer_v1_optimizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizer_v1_optimizer_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_optimizer_proto_depIdxs,
		MessageInfos:      file_optimizer_v1_optimizer_proto_msgTypes,
	}.Build()
	File_optimizer_v1_optimizer_proto = out.File
	file_optimizer_v1_optimizer_proto_goTypes = nil
	file_optimizer_v1_optimizer_proto_depIdxs = nil
}
