// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: orchestrator/v1/orchestrator.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "neuralops/api/proto/ai_engine/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *v1.PipelinePlan       `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	TaskCode      map[string]string      `protobuf:"bytes,2,rep,name=task_code,json=taskCode,proto3" json:"task_code,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map of task name to generated code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPipelineRequest) Reset() {
	*x = SubmitPipelineRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPipelineRequest) ProtoMessage() {}

func (x *SubmitPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPipelineRequest.ProtoReflect.Descriptor instead.
func (*SubmitPipelineRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitPipelineRequest) GetPlan() *v1.PipelinePlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SubmitPipelineRequest) GetTaskCode() map[string]string {
	if x != nil {
		return x.TaskCode
	}
	return nil
}

type SubmitPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPipelineResponse) Reset() {
	*x = SubmitPipelineResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPipelineResponse) ProtoMessage() {}

func (x *SubmitPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPipelineResponse.ProtoReflect.Descriptor instead.
func (*SubmitPipelineResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitPipelineResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_orchestrator_v1_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\"orchestrator/v1/orchestrator.proto\x12\x0forchestrator.v1\x1a\x1bai_engine/v1/pipeline.proto\"\xd7\x01\n" +
	"\x15SubmitPipelineRequest\x12.\n" +
	"\x04plan\x18\x01 \x01(\v2\x1a.ai_engine.v1.PipelinePlanR\x04plan\x12Q\n" +
	"\ttask_code\x18\x02 \x03(\v24.orchestrator.v1.SubmitPipelineRequest.TaskCodeEntryR\btaskCode\x1a;\n" +
	"\rTaskCodeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x16SubmitPipelineResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId2z\n" +
	"\x13OrchestratorService\x12c\n" +
	"\x0eSubmitPipeline\x12&.orchestrator.v1.SubmitPipelineRequest\x1a'.orchestrator.v1.SubmitPipelineResponse\"\x00B4Z2neuralops/api/proto/orchestrator/v1;orchestratorv1b\x06proto3"

var (
	file_orchestrator_v1_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_v1_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_v1_orchestrator_proto_rawDescData
}

var file_orchestrator_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orchestrator_v1_orchestrator_proto_goTypes = []any{
	(*SubmitPipelineRequest)(nil),  // 0: orchestrator.v1.SubmitPipelineRequest
	(*SubmitPipelineResponse)(nil), // 1: orchestrator.v1.SubmitPipelineResponse
	nil,                            // 2: orchestrator.v1.SubmitPipelineRequest.TaskCodeEntry
	(*v1.PipelinePlan)(nil),        // 3: ai_engine.v1.PipelinePlan
}
var file_orchestrator_v1_orchestrator_proto_depIdxs = []int32{
	3, // 0: orchestrator.v1.SubmitPipelineRequest.plan:type_name -> ai_engine.v1.PipelinePlan
	2, // 1: orchestrator.v1.SubmitPipelineRequest.task_code:type_name -> orchestrator.v1.SubmitPipelineRequest.TaskCodeEntry
	0, // 2: orchestrator.v1.OrchestratorService.SubmitPipeline:input_type -> orchestrator.v1.SubmitPipelineRequest
	1, // 3: orchestrator.v1.OrchestratorService.SubmitPipeline:output_type -> orchestrator.v1.SubmitPipelineResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_orchestrator_proto_init() }
func file_orchestrator_v1_orchestrator_proto_init() {
	if File_orchestrator_v1_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_orchestrator_proto = out.File
	file_orchestrator_v1_orchestrator_proto_goTypes = nil
	file_orchestrator_v1_orchestrator_proto_depIdxs = nil
}
